### ISSUE TITLE
Keep Alive Period not working

### ISSUE THREAD

**Issue by thebitrock** [unreal4u/mqtt#12]
```
$parameters->setKeepAlivePeriod(3);
```
Not working

Need set on create stream socket client, but in code set 60
```
stream_socket_client(
            $this->connectionParameters->getConnectionUrl(),
            $errorCode,
            $errorDescription,
            60,
            STREAM_CLIENT_CONNECT
        );
```

**Comment by unreal4u** [comment]
Hi! Thanks for reporting this.

In the next few lines of that function, the actual timeout is set: 
https://github.com/unreal4u/mqtt/blob/master/src/Client.php#L196

This is due to the fact that setting a timeout here applies only to the initial connection, but not to the rest of the requests, see https://www.php.net/manual/en/function.stream-socket-client.php (the timeout parameter explanation) for more information about this.

With a timeout this low, you can subscribe to a broker and check in the logs that every second a PINGREQ is being made.

I hope this answers your question, if you have more, don't hesitate to make them!

Greetings.
