### ISSUE TITLE
Update composer version

### ISSUE THREAD

**Issue by ghecho** [unreal4u/mqtt#8]
I just had a issue (PR #7) with a mismatch of the examples on master and the version published in composer. I assume it's because the latest tag is v0.3.0 and I would like to know if you could add a new version so the one in composer matches the latest examples or if this is because the next release is still in progress. 

Thanks in advance

**Comment by unreal4u** [comment]
Hi! 

For the time being, internal stuff is still being heavily modified, mainly because I'm implementing value objects now which I recently discovered. 

What I'll do is convert the connection parameters to use VO's (already half-way there) and then I think I'm ready to launch the first stable 1.0.0 version (I'll obvously check all examples at that point). From that moment on, I'll try to avoid backwards compatibility issues entirely. 

Implementing ssl ( #4 ) shouldn't be a bc issue in that point of time. 

Greetings and thanks for taking a look! This library will soon be ready!

**Comment by ghecho** [comment]
I see. Thanks for the quick response. I look forward to the updates. BTW, kudos for the library, what I’ve tried looks and works very well. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by unreal4u** [comment]
Hi! 

Just released v1.0.0-alpha which -while still not a stable release- is close enough to be like the final product will look like.

Closing this issue now 👍
